# Generated by Django 3.1.1 on 2020-09-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoecolor',
            name='color_name',
            field=models.CharField(choices=[('RED', 'Red'), ('ORA', 'Orange'), ('YEL', 'Yellow'), ('GRE', 'Green'), ('BLU', 'Blue'), ('IND', 'Indigo'), ('VIO', 'Violet'), ('WHI', 'White'), ('BLA', 'Black')], default='RED', max_length=3),
        ),
    ]
